language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-cpp-synchronization
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-drivers-can
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-net-https-client
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-subsys-usb-hid-mouse

# Zephyr framework doesn't support python 2
jobs:
  exclude:
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-cpp-synchronization
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-drivers-can
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-net-https-client
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-subsys-usb-hid-mouse
  

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: KS3aLW/Nc3q/XaEJzxKDfaK14OjZqTEeQdvOnlMZejG1g9ZerJP8QrZvmMcYXa4SkPBN7GQi3f0dZ+8Gpetik2fHre9EZBNCXwakWSsOqh5SG9/18cpJxiekFiK3tTWS6+HYTkVD1JcZZ3I6CbQIstObpcmJJWSGQ5O7ryePu2fDZOs3E4vqQbuxp0x80PrO70Cv6L/VVty3PkZCjplzg+bATddtCrNlc3NUAJkwwWeRNtndmWxeAMhwQDU92qFkQbXdCnRiW4OXXKf5AP/I67uTgDTIh3PW8OboYO75FqArz5nTXgTKcg75S7W74A6Xn3wGHgCu3EhIwwoVSV7fr8LNSItQcV2a6L3qs3WzfunlW7heSYB416TOWYOiAWMIUCXcEBf7niohSnZd3Gvrfmzha1LXF77kSnV9qJa+mWq4yOqlqPhJfQ4sCurig4lRj662W8rn9Sm8lMbx+1ah/aEptY7FhpEqHwAZ7BAaxfI7UBww9xaInnWCw5Xa4sAvZyy8E2MDeGo26Dp5G+qDMdsY4vODABquB9X+EdToYSyXiHFfKpLhxPQ9pM9s1mPFBTRtDB9dyM85kU0U6NnvTQwXSXFF4/Z44TagwUDhoiB3GgY9qYjyNxtNVkYFCi/W2fW2qW5AXqJGLMNvujhqj7R8x0Oj5/QfMhphRdmNFyE=
    on_failure: always
    on_success: change
